name: Docker Compose workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up --build -d
    - name: Newman backend test
      run: cd backend && npm run integration-test-local
    - name: Project feature test
      run: cd backend && npm run project-test
    - name: US feature test
      run: cd backend && npm run us-test
    - name: Misc test
      run: cd backend && npm run misc-test
